"""
Direct Fracture Localization Diagnostic Tool
===========================================
Usage:
    python test_localization.py --image path/to/fracture.jpg [--score-thresh 0.25]
"""

import os
import sys
import argparse
import json
import torch
from PIL import Image
import torchvision.transforms.functional as TF

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '.')))

from inference.model_registry import ModelRegistry
from inference.localization_predictor import LocalizationPredictor
from inference.preprocessing import preprocess_for_detector

def test_direct_localization(image_path: str, score_thresh: float = 0.25):
    if not os.path.exists(image_path):
        print(f"Error: Image file does not exist: {image_path}")
        sys.exit(1)

    device = ModelRegistry.get_device()
    print(f"Running direct localization on: {image_path}")
    print(f"Device: {device} | Confidence Threshold: {score_thresh}")

    predictor = LocalizationPredictor(score_thresh=score_thresh, device=device)
    if not predictor.is_available:
        print("ERROR: Localization detector could not be loaded!")
        print(f"localization_model_loaded: False")
        print(f"localization_model_path: {ModelRegistry.DETECTOR_CHECKPOINT_PATH}")
        sys.exit(1)

    print(f"localization_model_loaded: True")
    print(f"localization_model_path: {ModelRegistry.DETECTOR_CHECKPOINT_PATH}")
    print(f"localization_model_classes: {ModelRegistry.DETECTOR_NUM_CLASSES} (0=Background, 1=Fracture)")

    # 1. Run raw inference through model to inspect proposals before any thresholding
    tensor, (orig_w, orig_h) = preprocess_for_detector(image_path)
    tensor = tensor.to(device)

    with torch.no_grad():
        raw_preds = predictor.model(tensor)[0]
        raw_boxes = raw_preds['boxes'].cpu().numpy()
        raw_scores = raw_preds['scores'].cpu().numpy()
        raw_labels = raw_preds['labels'].cpu().numpy()

    print("\n--- RAW DETECTOR OUTPUT BEFORE THRESHOLDING ---")
    print(f"Total raw proposals generated by Faster R-CNN: {len(raw_scores)}")
    if len(raw_scores) > 0:
        print(f"Top 5 raw scores: {raw_scores[:5].tolist()}")
        print(f"Max raw confidence: {float(raw_scores[0]):.4f} (Label: {int(raw_labels[0])})")
    else:
        print("No raw proposals generated!")

    # 2. Filter using score threshold
    valid_mask = (raw_scores >= score_thresh) & (raw_labels == 1)
    filtered_boxes = raw_boxes[valid_mask]
    filtered_scores = raw_scores[valid_mask]
    filtered_labels = raw_labels[valid_mask]

    scale_w = orig_w / float(predictor.target_size[0])
    scale_h = orig_h / float(predictor.target_size[1])

    final_boxes = []
    final_scores = []
    final_classes = []

    for box, score, label in zip(filtered_boxes, filtered_scores, filtered_labels):
        x1 = round(float(box[0] * scale_w), 1)
        y1 = round(float(box[1] * scale_h), 1)
        x2 = round(float(box[2] * scale_w), 1)
        y2 = round(float(box[3] * scale_h), 1)
        final_boxes.append([x1, y1, x2, y2])
        final_scores.append(round(float(score), 4))
        final_classes.append("Fracture" if label == 1 else f"Class_{label}")

    number_of_detections = len(final_boxes)

    print("\n--- FINAL FILTERED DETECTION RESULTS ---")
    print(f"number_of_detections = {number_of_detections}")
    print(f"boxes = {final_boxes}")
    print(f"scores = {final_scores}")
    print(f"classes = {final_classes}")

    if number_of_detections == 0:
        print("\n[DIAGNOSTIC] number_of_detections = 0:")
        if len(raw_scores) > 0:
            max_s = float(raw_scores[0])
            print(f"  -> Model generated proposals, but highest score ({max_s:.4f}) is below threshold ({score_thresh}).")
            if max_s >= 0.05:
                print(f"  -> Sub-threshold candidate exists at score {max_s:.4f}. Consider checking lower thresholds.")
        else:
            print("  -> RPN produced zero regions.")

    # 3. Also verify predict() standard pipeline method
    pipeline_res = predictor.predict(image_path, fracture_detected=True)
    print("\n--- PREDICTOR.PREDICT() CONTRACT CHECK ---")
    print(f"localization_available: {pipeline_res['localization_available']}")
    print(f"localization: {pipeline_res['localization']}")

    return {
        "number_of_detections": number_of_detections,
        "boxes": final_boxes,
        "scores": final_scores,
        "classes": final_classes,
        "localization_available": pipeline_res['localization_available']
    }

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="Direct Fracture Localization Diagnostic Tool")
    parser.add_argument('--image', type=str, required=True, help="Path to input radiograph")
    parser.add_argument('--score-thresh', type=float, default=0.25, help="Confidence score threshold")
    args = parser.parse_args()

    test_direct_localization(args.image, score_thresh=args.score_thresh)
